### ISSUE TITLE
Postgres 502 Bad Gateway on flush()

### ISSUE THREAD

**Issue by kokojar** [dunglas/symfony-docker#142]
I have a private project that uses postgresql. Everything worked very well so far. I put the project up again a month ago and there were no problems.

Now when I tried to set a project on a new server when creating (register by form or command) a new user or create  a new product on the site I get a 503 error. This only happens with postgresql.

To confirm, on the old working server I did

```
docker system prune -a
docker-compose up 
```

and the problem suddenly appeared on the old server.

I tried debugging and the script ended up trying to executeInserts () UnitOfWork.php

To confirm that this is not a problem with my code, I went back to an older commit, but the problem still persists. Can you verify this in your projects, please?

**Comment by maxhelias** [comment]
This problem is not related to this project because postgresql is not integrated here.

To try to help, you probably have a postgresql version compatibility issue, if you have not defined a specific version. When you used the 'docker system prune' command, you erased the build made at the time maybe with version X and rebuilding a new one today could be with version X+1.
