### ISSUE TITLE
symfony.wip doesnt work

### ISSUE THREAD

**Issue by gponty** [dunglas/symfony-docker#189]
Hi,
I tried to start docker-compose with SERVER_NAME="symfony.wip, caddy:80", but it dont work, i have many errors :

Error creating new order :: Cannot issue for \"symfony.wip\": Domain name does not end with a valid public suffix (TLD)
error":"[symfony.wip] Obtain: [symfony.wip] creating new order: attempt 1: https://acme.zerossl.com/v2/DV90/newOrder: HTTP 400 urn:ietf:params:acme:error:rejectedIdentifier - Invalid DNS identifier [symfony.wip]

and of course a browser error : ERR_SSL_PROTOCOL_ERROR

But with symfony.localhost that's work, any idea ?
thank you

**Comment by rowanparker** [comment]
My understanding:

`.wip` should not work, because (as the error says) it's not a valid public suffix.  See this page, where `.wip` does not exist https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains#W

You should be setting the SERVER_NAME to your production domain (e.g. example.com), but only do that in the production environment.

This project doesn't use the Symfony web server. Is there a reason you can't use `localhost` in the development environment?

**Comment by gponty** [comment]
Thx for your reply, i understand now.
I can have many projects running at the same time, but i will use in dev env projetct1.localhost, project2.localhost...
Thank you !
