### ISSUE TITLE
Custom local server name on Windows

### ISSUE THREAD

**Issue by quentint** [dunglas/symfony-docker#209]
Hi and thank you for this awesome repo!

I'm working an a webapp where some features depend on the subdomain. When working locally I would need at least two of them, which could look like these: `this.my-app.wip` and `that.my-app.wip`.

I read the docs and could not figure out how to do that on Windows. Is there a guide somewhere in the wild? Or can I help write one if you have some pointers to help me do that?

Thanks!

**Comment by Muspi** [comment]
Hi, i'm interested too

**Comment by SanderVerkuil** [comment]
Like everything, you can do this in a multitude of ways. The simplest here would be to add an entry to `C:\Windows\System32\drivers\etc` with:

```
127.0.01  this.my-app.wip that.my-app.wip
```

If you want to have a custom tld like `.wip` that points to localhost, there are a couple of things you can do. But according to the [valet windows](https://github.com/cretueusebiu/valet-windows) project the [Acrylic DNS](https://mayakron.altervista.org/support/acrylic/Home.htm) appears to be a good bet, where you should be able to specify something like:

```
127.0.0.1 *.wip
::1 *.wip
```

which makes sure that all domains ending in `.wip` are matched to be your local machine.

Do note that only one container can expose to port 80. If you want to have multiple websites/api's available with https://foo.wip and https://bar.wip you're going to have to use a reverse proxy that will proxy the domains to the correct containers. In order to do that, take a look at [this project](https://hub.docker.com/r/jwilder/nginx-proxy).
