### ISSUE TITLE
Docker cache issue

### ISSUE THREAD

**Issue by vasilvestre** [dunglas/symfony-docker#216]
Today as I deployed, I had a problem with a dependency during cache warmup after upgrading to 6.0.
Our dependency was updated in the source code but some layer issues made our service unusable until I stopped and remove the docker container.
The production deployment guide may specify to use --no-cache in order to avoid this issue maybe? Otherwise, --force-recreate, I'm not sure as I solved it without docker-compose

**Comment by Vandersteen** [comment]
I've had the same issue.
This was after installing a new dependency and 'redeploying' to prod.
I'm starting to believe that this line is the culprit:
 
https://github.com/dunglas/symfony-docker/blob/9e5544753c1cad48f5e082e8b07f13b57b746744/Dockerfile#L99

The dependency was installed correctly, but the cached 'classmap' was out of wack.

I had to 'delete' the image and rebuild in order to fix it

**Comment by momen573** [comment]
Hello I have this issue when runing docker
 => CANCELED [app_caddy_builder 2/2] RUN xcaddy build  --with github.com/dunglas/mercure  --with github.com/dunglas/mercure/caddy  --  120.2s

**Comment by maxhelias** [comment]
I've added a note about it here : https://github.com/dunglas/symfony-docker/issues/216
