### ISSUE TITLE
Could you please help me. I tried for 2 days and I really couldn't figure it out

### ISSUE THREAD

**Issue by azadky** [dunglas/symfony-docker#302]
I clone the project to the desktop. It works fine on my computer at work. However, on my home computer, it gives an error as follows. I couldn't figure out the reason even though I tried hard, I would be very happy if you could help.

#0 10.70 curl: (6) Could not resolve host: objects.githubusercontent.com

 > [symfony-docker-php app_php  6/21] RUN set -eux;     install-php-extensions          intl            zip             apcu            opcache     ;:
#0 0.707 + install-php-extensions intl zip apcu opcache
#0 0.714 install-php-extensions v.1.5.42
#0 0.714 #StandWithUkraine
#0 10.70 curl: (6) Could not resolve host: objects.githubusercontent.com
------
failed to solve: executor failed running [/bin/sh -c set -eux;     install-php-extensions       intl            zip             apcu            opcache     ;]: exit code: 6

**Comment by maxhelias** [comment]
This seems a network connection issue and it's not something we control. Make sure you don't have a proxy.

Otherwise, try another version of php it can sometimes come from the image that is downloaded.

**Comment by azadky** [comment]
Thanks you so much.

**Comment by tkant** [comment]
This issue is happening because of DNS resolution failures from within containers, you might notice `getaddrinfo` failing while making curl request to sites which only serves on IPv4. 
### Core problems:
1. Alpine uses UDP over TCP for resolutions
2. It tries to resolve IPv6 in parallel to IPv4

### Resolution:
Move away from alpine to debian (buster or bullseye) based image

More reads:
https://github.com/alpinelinux/docker-alpine/issues/149 
https://www.weave.works/blog/racy-conntrack-and-dns-lookup-timeouts
