### ISSUE TITLE
server reached pm.max_children setting (5), consider raising it

### ISSUE THREAD

**Issue by ZiadNOsman** [dunglas/symfony-docker#326]
I'm occasionally getting the following warning in my php container, afterwards the server stops accepting any connections and I need to replace the server.

`[pool www] server reached pm.max_children setting (5), consider raising it
`
What's weird is that, I checked the logs and the load on the server at the time wasn't that high (15%) and there were no database connections at the time. 

I'm wondering what is causing this warning to come up, and how to raise the max_children setting. 

I could not find the fpm file to change this value, so I'm wondering if I'm missing something, or If I have to modify the Dockerfile somehow to add a command to raise the number of max_children on container creation.

I'm using AutoScaling which spins up images of my container, so any solution I come up with needs to work automatically, without having to modify the container after creation.

**Comment by maxhelias** [comment]
Hello,
This appears because your server has reached the process count event if it still has some RAM left.
In this case, it is wise to adjust the `pm.max_children` according to the size of your server (https://myshell.co.uk/blog/2012/07/adjusting-child-processes-for-php-fpm-nginx/).

You can find the config file here `/usr/local/etc/php-fpm.conf`, it is provided by the default php fpm image. And this file includes all the files that are put in the folder `/usr/local/etc/php-fpm.d/`, this is what we do in this project with this file : https://github.com/dunglas/symfony-docker/blob/main/docker/php/php-fpm.d/zz-docker.conf
