### ISSUE TITLE
Base images on Docker Hub?

### ISSUE THREAD

**Issue by back-2-95** [dunglas/symfony-docker#332]
Could there be build Docker images from Dockerfile in Docker Hub?

It could fasten ppl starting their own projects from them.

**Comment by maxhelias** [comment]
This is complicated on our side because we deliver only a docker skeleton for Symfony without application.
To have an effective cache with DockerHub, it mush be pushed with a build where an application is present. And as everyone has different application/version and configuration it would cause a lot of problems.
