### ISSUE TITLE
xdebug

### ISSUE THREAD

**Issue by vladislavs1321** [dunglas/symfony-docker#34]
Hello, 
is it possible to have some preconfigured optional possibility to have xdebug here?

**Comment by hacfi** [comment]
@vladislavs1321 Try adding the following to the Dockerfile:

```
RUN set -ex \
 && pecl install xdebug \
 && docker-php-ext-enable xdebug \
 && echo "[xdebug]"                   | tee -a /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
 && echo "xdebug.idekey=PHPSTORM"     | tee -a /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
 && echo "xdebug.remote_autostart=on" | tee -a /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
 && echo "xdebug.remote_enable=on"    | tee -a /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
 && echo "xdebug.remote_port=9000"    | tee -a /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

ARG DOCKER_HOST_IP=172.18.0.1
RUN echo "xdebug.remote_host=${DOCKER_HOST_IP}" | tee -a /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
```

`DOCKER_HOST_IP` needs to be set so that the container connects to your host. If you use network mode host it's 127.0.0.1. If not use `docker network inspect {your_network_id}` and use the gateway ip (you can try the following command to get it directly: `docker network inspect --format '{{(index (index .IPAM.Config) 0).Gateway}}' NETWORK_ID`).

For CLI debugging add also:
```
ENV XDEBUG_CONFIG "idekey=PHPSTORM"
ENV PHP_IDE_CONFIG "serverName=yourhostname.local"
```

**Comment by vladislavs1321** [comment]
@hacfi , thanks for this example, but maybe make sense  somehow include this into Dockerfile by default?

**Comment by jewome62** [comment]
@vladislavs1321 IMOO
there is no interests to do that, because for me this repository is a starter pack to beginning a Symfony Project with Docker. So with the the strict necessary to have a running project.
Xdebug is not used by all developers. Xdebug is heavy. And Xdebug is not recommended in production.
So if someone want have xdebug, he can add into his dockerfile.

So Maybe do a PR to add some documentation ?

**Comment by vladislavs1321** [comment]
@jewome62 yep, im understand this point, but i would like to have possibility out of the box start writing some php unit tests and have coverage report, so maybe it is ok to do something like 
```
FROM symfony_docker_php as dev

RUN apk add --no-cache --update --virtual buildDeps autoconf gcc make g++ \
	&& pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && echo 'zend_extension="/usr/local/lib/php/extensions/no-debug-non-zts-20170718/xdebug.so"' >> /usr/local/etc/php/php.ini

COPY docker/app/xdebug.ini $PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini
``` 
im not so expert in configuring images, but i think it make sense for speed up development, 
so in docker-compose it's possible to use `dev` build context.

**Comment by maxhelias** [comment]
I think it's possible with a new target PHP specific for development mode.
