### ISSUE TITLE
`docker compose up --wait` does not detach, `-d` required

### ISSUE THREAD

**Issue by jurchiks** [dunglas/symfony-docker#436]
The latest commit replaced `-d`/`--detach` with `--wait`, however it does not seem to work the way the documentation says it should, at least not on Windows.

According to Docker's own documentation (https://docs.docker.com/engine/reference/commandline/compose_up/):

>`--wait`		Wait for services to be running|healthy. ***Implies detached mode.***

One might think this means that it runs the services, waits for them to be fully up, and THEN detaches _implicitly_, without requiring an explicit `-d` flag. However, if I run it with just  `--wait`, it does not detach. One might say the documentation is wrong or incorrectly worded - wouldn't be the first time -, or maybe it's broken on Windows (I had Docker Desktop 4.21.1, updated to 4.22.0, still the same).

But then I found this article: https://maciejwalkowiak.com/blog/docker-compose-waiting-containers-ready/

And if I use `--detach --wait`, then it works as it should, so the code and documentation changes from the latest commit should be fixed.

Annoyingly, I tried clicking on "Edit this page" in the Docker documentation, but it lead me nowhere, and searching the repo it opened for `Implies detached mode` gave me no results, so I can't fix the wording myself.

**Comment by dunglas** [comment]
Thanks for the report. The docs are here (the link on their website is indeed broken): https://github.com/docker/compose/blob/v2/docs/reference/compose_up.md

This works as expected on my computer (Docker Desktop on macOS), IMHO this bug should be reported to Docker instead of here, but I'm not against adding `--detach` to the command.

**Comment by jurchiks** [comment]
> This works as expected on my computer

Interesting... Well, I'm sure Docker isn't going to fix this anytime soon, so it's probably best to add it back for now.

**Comment by core1983** [comment]
In my case this command also not working properly. I'm using docker inside wsl distro, without installing docker desktop.

**Comment by 7-zete-7** [comment]
Hi, @jurchiks, @core1983!

Sorry for reviving this issue after so long since it was closed 😅

@lermontex [brought](https://github.com/dunglas/symfony-docker/pull/778#pullrequestreview-2754394307) this issue to my attention and was curious about this behavior of Docker Compose. I'm trying to figure out a possible reason for this behavior to figure out the issue. Can you reproduce this issue now? Is it possible that you were using Docker Compose v1?

**Comment by 7-zete-7** [comment]
Thanks for your help, @ndeloof!

**Comment by jurchiks** [comment]
Then perhaps the problem is caused by WSL. Wouldn't be the first time, unfortunately...
