### ISSUE TITLE
Best Practices for Running Containers as Non-Root in Production?

### ISSUE THREAD

**Issue by MichaelBrauner** [dunglas/symfony-docker#443]
First off, thank you for providing such a valuable tool in the Symfony Docker setup. 

I came across the ["running as root" topic](https://github.com/dunglas/symfony-docker/issues/132) in the containers.
 
While I understand the simplicity it provides, especially during development, I'm curious about the recommended approach for production environments.

From the discussions I've seen, there seems to be a mix of practices. Some people seem to be comfortable running as root, while others try to set up a non-root user, facing various challenges in the process.

Could you shed some light on what you consider to be best practices for production? Specifically:

- Do you generally recommend running the containers as root in production or is there a preferred, safer method? If the recommendation is to run with a non-root user, do you have any guidance or documentation on setting this up seamlessly?

- I truly believe that a clearer understanding of this would benefit many in the community, ensuring safer deployments and configurations.

Thank you in advance for your time and insights.

**Comment by maxhelias** [comment]
Hello, thank,

I don't use containers in production, so I won't be able to give you my feedback because I use this project in dev and ci occasionally.

But I think @dunglas can give you some feedback on recommendations.

**Comment by 7-zete-7** [comment]
Hello everyone.

I agree with @MichaelBrauner. I'm also interested in this issue.

In my case I run this solution as a non-root via:

- adding `su-exec` `apk`-package on Dockerfile:

```diff
 RUN apk add --no-cache \
 		acl \
 		file \
 		gettext \
 		git \
+		su-exec \
 	;
```

- adding ACL rights to `www-data` user on `/data` and `/config` dirs in `docker-entrypoint`:

```diff
-	setfacl -R -m u:www-data:rwX -m u:"$(whoami)":rwX var
-	setfacl -dR -m u:www-data:rwX -m u:"$(whoami)":rwX var
+	setfacl -R -m u:www-data:rwX -m u:"$(whoami)":rwX var /data /config
+	setfacl -dR -m u:www-data:rwX -m u:"$(whoami)":rwX var /data /config
```

- adding `su-exec` executing (instead of `exec`) on end of `docker-entrypoint`:

```diff
-exec docker-php-entrypoint "$@"
+su-exec 'www-data:www-data' docker-php-entrypoint "$@"
```

However, there is still a question about the security of the `/data` and `/config` directories.

Are there more elegant and secure ways to avoid running the server as the root?
