### ISSUE TITLE
Bind for 0.0.0.0:443 failed: port is already allocated

### ISSUE THREAD

**Issue by cleargoal** [dunglas/symfony-docker#455]
I run the command `docker compose up --pull --wait`
and got the error.
>  ⠿ Container symfony-docker-caddy-1  Starting                                                                                                                                 0.6s 
Error response from daemon: driver failed programming external connectivity on endpoint symfony-docker-caddy-1 (ec075b675ec774d27afd137549fbe4543f7a4653eda3f538493f0e07f3dc0411): Bind for 0.0.0.0:443 failed: port is already allocated

What is the right way to change that port?

**Comment by cleargoal** [comment]
> Hello,
> 
> Please keep this board for project-related issues. It's a common issue that has already been answered several time on different forums.
> 
> You already have another service running on port 443. It could be another container, a web server or something else. You need to find out what it is and turn off.
> 
> Sorry i can help you more.

I don't want to turn off another container. I need this container to run on another port.
But you are right - there is info contained in other issues.
Sorry for disturb.

**Comment by maxhelias** [comment]
Don't worry, sorry if my message upset you

**Comment by zpi12lmm** [comment]
This problem usually occurs when you are trying to run a development project because you may have more than one web server with the same port.
Docker itself assumes such a case, and therefore to solve this problem, you can specify your own port, or allow docker to choose a random port on its own.
For example, to manually specify the desired port (let it be 4433), run the following command` HTTPS_PORT=4433 docker compose up --pull --wait`, and if you want to get a random port when starting the project, then go to the docker-compose.yml file, find the value `${HTTPS_PORT:-443}`, and replace it with the following `${HTTPS_PORT:-}`, and run the following command `docker compose up --pull --wait` (in addition, you can also specify your preferred port using HTTPS_PORT to override the random port that was assigned by docker).

**Comment by mahmoudsaeed** [comment]
> This problem usually occurs when you are trying to run a development project because you may have more than one web server with the same port. Docker itself assumes such a case, and therefore to solve this problem, you can specify your own port, or allow docker to choose a random port on its own. For example, to manually specify the desired port (let it be 4433), run the following command` HTTPS_PORT=4433 docker compose up --pull --wait`, and if you want to get a random port when starting the project, then go to the docker-compose.yml file, find the value `${HTTPS_PORT:-443}`, and replace it with the following `${HTTPS_PORT:-}`, and run the following command `docker compose up --pull --wait` (in addition, you can also specify your preferred port using HTTPS_PORT to override the random port that was assigned by docker).

If, like me, you are trying to run multiple symfony-docker apps on the same machine, you will also need to override the values of `HTTP_PORT` and `HTTP3_PORT` to avoid the error.
