### ISSUE TITLE
[Question] When cache folder isn't shared with the host, how to use PhpStorm Symfony plugin?

### ISSUE THREAD

**Issue by anyt** [dunglas/symfony-docker#48]
Hi, 
I'm trying to use this repository on MacOS and Windows.

PhpStorm Symfony plugin is handy during development, but it's relying on the cache folder content. With the default configuration, `var/cache` folder is excluded from sync.

When I remove the cache folder from volumes config to make it sync with the host - everything is slowing down by 2-5 times.
I already tried NFS volume and docker-sync, the performance still is not as good as with nonshared cache. At least for me, it is two times slower in the best scenario.

*Maybe someone here is using this repository on MacOS or Windows with PhpStorm Symfony Plugin successfully and knows how to reduce performance degradation?*

**Comment by B-Galati** [comment]
I think a good middle-ground would be to have something that would sync the cache folder of the container to the host from time to time. On my hand I was not able to find any good solution for my colleagues running on MacOS.

**Comment by maxhelias** [comment]
Some of my colleagues have started using Mutagen : https://mutagen.io/
I do not have a feedback yet

**Comment by karousn** [comment]
@maxhelias : any feedback now ?

**Comment by maxhelias** [comment]
@karousn no.. sorry :/

**Comment by maxhelias** [comment]
FYI docker for mac on edge has a new file sharing using Mutagen.
More information here : https://docs.docker.com/docker-for-mac/mutagen-caching/

**Comment by maxhelias** [comment]
Since Docker Desktop 2.3.5.0, now uses gRPC-FUSE for file sharing by default. "Which promises performance between osxfs and mutagen."
More information about gRPC-FUSE here : https://www.docker.com/blog/deep-dive-into-new-docker-desktop-filesharing-implementation/
Follow the improve Mac File system performance : https://github.com/docker/roadmap/issues/7

As we have no other solution than to use the native system, mutagen or docker-sync, I close this issue

**Comment by maxhelias** [comment]
If you want to try mutagen, follow this issue : https://github.com/mutagen-io/mutagen/issues/235
