### ISSUE TITLE
Symfony is very slow in dev mode

### ISSUE THREAD

**Issue by Saintchicky** [dunglas/symfony-docker#509]
Hello everyone!
I am stuck when I uncomment the line - /app/vendor to improve Symfony's performance under Windows.
In the php container logs, I have this:
Fatal error: Uncaught LogicException: Symfony Runtime is missing. Try running "composer require symfony/runtime". in /app/bin/console:8
Indeed, we remove it from the bind mount, but then, I can't find the next step.
Thank you for your help!

**Comment by dunglas** [comment]
Can you install the missing package?

**Comment by Saintchicky** [comment]
Thank you for responding.
I do have my vendor installed with the runtime dependency.
If I don't uncomment the line - /app/vendor, the project works but it's very slow (the home page, which doesn't have any database queries, just a small jpg image: 19404ms, and when I refresh it's 9800ms by the Symfony Profiler)
An additional piece of information, I don't have composer and php installed on my computer.
I have installed Turbo, and when I do a scroll, it takes between 10000ms and 9000ms.
https://symfonycasts.com/screencast/symfony-doctrine/forever-scroll

**Comment by ili101** [comment]
> Realistically what we would all want is that the `/app/vendor` folder is only synced one way: container -> host

@jurchiks I have a question because I work differently (with devcontainer). what is the point of having the vendor folder on the host and using Docker?
If you have already installed all the dependencies to run the project locally why do you also use Docker locally?

Also, I'm not familiar with Mac but on Windows, if you put your project folder in your WSL Ubuntu partition, mounting or not mounting the folder to Docker should have a similar performance.

**Comment by jurchiks** [comment]
@ili101 I haven't tried putting the folder in WSL, guess I should try that. I read about it but somehow forgot...

As for devcontainer - I tried setting that up, but PHPStorm didn't (or maybe stll doesn't) support devcontainers, and I need the vendor folder for the code analyzer, otherwise everything's red.

**Comment by ili101** [comment]
> @ili101 I haven't tried putting the folder in WSL, guess I should try that. I read about it but somehow forgot...
> 
> As for devcontainer - I tried setting that up, but PHPStorm didn't (or maybe stll doesn't) support devcontainers, and I need the vendor folder for the code analyzer, otherwise everything's red. The dumb thing still has no support for just reading the vendor folder contents from the container like VS Code does, afaik.

I made a fork with Devcontainer https://github.com/dunglas/symfony-docker/pull/523. works nicely with VSCode.
I don't use PhpStorm but I see that they added support for Devcontainer but it doesn't work for me, probably because of [alpine support](https://youtrack.jetbrains.com/issue/IDEA-333138/DevContainers.-Failed-dev-containers-creation-on-images-without-necessary-dependencies)

**Comment by maxhelias** [comment]
The performance problems are not linked to this project but to the management of the Docker flysystem on the different OS, which are very different.
Window is known for having the worst performance and we can't do anything about it on our own.
Thank you for your understanding.
