### ISSUE TITLE
[Docs] List known Alpine issues

### ISSUE THREAD

**Issue by KDederichs** [dunglas/symfony-docker#586]
Hey,

I was wondering if it was possible to list what exactly the known issues mentioned in https://github.com/dunglas/symfony-docker/blob/main/docs/alpine.md are.

I feel like it would help users with the decision if they should use Alpine or not.

**Comment by maxhelias** [comment]
If I have understood correctly the problem is that Alpine and Debian use different C standards: `musl` on Alpine vs `glibc` on Debian, and PHP depends heavily on this.
As mentioned here: https://github.com/dunglas/symfony-docker/issues/555 it creates instabilities with PHP because it hasn't tested with musl.
IMO, the real question is why do you use Alpine? Is it representative of your production environment?

**Comment by dunglas** [comment]
See this thread for some details: https://x.com/dunglas/status/1767846666638430356?s=20
