### ISSUE TITLE
Could we prevent our code from our app to mix with this one ?

### ISSUE THREAD

**Issue by BaptisteCrouzet** [dunglas/symfony-docker#97]
Hello,

I'm not sure if it's appropriate to ask this here.
The structure offered by this repository seems to me strange againt some tutorial found in order to make a symfony-docker. For example this one : https://dev.to/martinpham/symfony-5-development-with-docker-4hj8 

Thus there is my question why put the Symfony's code at the root and not inside a "public" folder (or "www", "web", "src") ?
We juste have to move the mount point, same for Caddy, and maybe in the entrypoint script (I didn't tried with this file).
It can help us to split our code in two repositories and not mix them.

If possible, maybe I can make a PR in this way ?

I propose to rename public/ folder into src and move the mount point of our app inside this folder.

Thank you, for your response.
(sorry for my english)

**Comment by maxhelias** [comment]
Hi @BaptisteCrouzet,

I think this is the right place to ask 😉 

Why does she seem strange to you ?
Have you done a complete installation of the project or read the documentation ? I think that after these it will seem less strange to you (well I hope).

In fact, if we rename the "public" folder to "src", we will have a path like this one : `~/my-project/src/src` to access the project source because this project automatically installs a symfony or reuses your symfony at the root.
This has the advantage of being able to use Flex to configure new services via the recipes system.

Do not hesitate if you still have questions. And I'm available on the Slack in French if needed 😉  

Thanks

**Comment by dunglas** [comment]
And if you prefer to store your app on a subdirectory, take a look to https://GitHub.com/api-platform/api-platform. It's almost the same setup, but using a subdirectory (and with API Platform and Next.js preinstalled, but you can remove them if necessary).

**Comment by BaptisteCrouzet** [comment]
Thanks for your responses !

I tried a little more to work with your project, and and I really understood the aim to have my code here and not in a subdirectory when I tried to add a database !
I understood the strenght of Flex recipes when it modified my `Dockerfile` 🙂.
Maybe I lack of a little more experience and I didn't understand right away when I tried it.

And yes I didn't think when I proposed "src", it was not a good proposal.

API Platform is good example too thank you !

PS: I wanted to keep two different repositories, one for docker and one for my app, but it doesn't seem so bad to me either. There are real advantages too follow your direction.
